# Generated by Django 3.0.7 on 2020-08-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200823_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klasa',
            old_name='pershkrimi',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='klasa',
            old_name='imazhi',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='klasa',
            old_name='titulli',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='titulli',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='titulli',
            new_name='title',
        ),
    ]
