# Generated by Django 3.0.7 on 2020-08-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200825_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lendet',
            old_name='pershkrimi',
            new_name='description',
        ),
    ]
