# Generated by Django 3.0.7 on 2020-08-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200825_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Klasa',
            new_name='Classs',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='klasa',
            new_name='classs',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='krijuar_me',
            new_name='created_with',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='krijues',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='imazhi_lendes',
            new_name='image_case',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lenda',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='pozicioni',
            new_name='position',
        ),
    ]
