# Generated by Django 3.0.7 on 2020-08-25 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0019_auto_20200825_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lendet',
            new_name='Subjects',
        ),
    ]
