# Generated by Django 3.0.7 on 2020-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20200825_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='image_case',
            field=models.ImageField(default='default.jpg', upload_to='course_images'),
        ),
    ]
